### ISSUE TITLE
Reversing the Optimizations / Allowing Windows Store apps?

### ISSUE THREAD

**Issue by rblancojr** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#105]
Hi Is there a way to perform a process to reverse the optimization process on a WVD host?

Unfortunately, not having the Windows Store apps has caused usability issues for a deployment. The users actually need Windows Calculator and the Windows Media player as an example.

Attempts for the user to reinstall the Windows Store app ends in unusual behavior where if the user installs Calculator as an example, it is not available for their current session. Once they logoff and logon again, the Store apps are no longer available and even a taskbar pin to the app no longer works. I assume this may be some Local policy or similar, but not sure where to start to check.

My initial thoughts were to reverse the entire process but not sure that is even possible?
Open to recommendations.

Thanks
Richard

**Comment by rajneeshsaraswat** [comment]
please let us know if this can be possible

**Comment by tmmuessig** [comment]
As an administrator, you should be able to reinstall any of the store apps and have them persist through logoffs for the users.

In regard to reversing the entire process, this is not something we have attempted to do at this point.

**Comment by rsavard-tt** [comment]
I'm struggling with this as well.  I want to reactivate the "Photos" app that was previously removed by the optimizer.

If I log in as the local admin and install it via the Store app, it only seems to get installed for the current user (local admin). When another user logs in and they don't see it.

**Comment by robsmi-msfte** [comment]
We have this behavior documented in the README.MD file.  The VDOT tool makes 3 passes on every UWP app that has the parameter set to "Disabled":

1. Remove the UWP app for current user
2. Remove the UWP app for all users
3. Remove the UWP payload

The app can be reinstalled on a per-user basis.  But once the payload itself has been removed, it is no longer available globally.  Further, there is no way that we know of to restore a UWP app payload.  I worked on this extensively and went to dev teams on this and that was the result.  That is why we don't remove the Store app, nor recommend it be removed.

Currently the only way to "reverse" these settings is reimage or reinstall.  That's why we stress multiple times in multiple places...test...test...test.
