### ISSUE TITLE
Removed Store Apps Remain on Start Menu

### ISSUE THREAD

**Issue by benjohnsonofgem** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#148]
Hi guys, me again :)

So, with my latest image, we have run the latest version of VDOT and removed all Store Apps, only leaving a few. This persists through reboot. After capturing the image in Azure and using that to then populate an AVD pool, upon login, all of the icons for the removed apps remain in the Start Menu. When clicked, it redirects to the Store, as obviously they have been removed.

Ben

**Comment by robsmi-msfte** [comment]
Hello @benjohnsonofgem,

We have seen this behavior, documented it, and have a possible repair script here:

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#start-menu-broken-links-10132020

I haven't used that one for a while, and it may need to be modified for current builds.  I believe the issue is far less prevalent when a new profile is created for the first time, AFTER a host has been optimized.  There still may be a blank icon for Office.

I have found a different interested way to "fix" this behavior.  By using a Start Menu layout file, and creating 1 group, you can direct the behavior to first clear the Start Menu, then laydown the new layout.  The groups that you specify in the layout file cannot be user modified.  But users can still pin and so on to the Start Menu.

The Start Layout process involves creating a Start Layout file (.xml), put it somewhere accessible to OS (I put it in \Windows\System32), then set local policy or registry setting to make the change take effect.  You don't have to do the Taskbar if you don't want, and can still have your customized Start Menu, while still allowing users to pin things to it and those pins persist in their profile.

Thanks,

Robert Smith

**Comment by BenJ180** [comment]
Thanks Robert. Yes, I did pick up that you had a known issue and fix for icons remaining on the Start Menu, I didn't see it before I posted. My most recent builds haven't shown the same symptoms, but I will attempt the script if I encounter it again. Thanks, Ben.
