### ISSUE TITLE
Feature Request: Provide the ability to remove PowerShell v2.0 Feature

### ISSUE THREAD

**Issue by brmcmill** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#168]
Hey Team -- this is probably more of a security/hardening requirement.  Would it be feasible to ask if we can have a switch to remove the PowerShell v2.0 feature?  Some code that may work for Single-Session/Multi-Session hosts in AVD:

```PowerShell
    Write-Host "Attempting to disable PowerShell v2.0."
    if ($(Get-CimInstance Win32_OperatingSystem).ProductType -eq "1")
    {
        # Disabled PowerShell v2 for Workstation/Single-Session SKU
        Disable-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2Root -ErrorAction Stop | Out-Null
        Write-Host "Powershell v2.0 feature has been disabled."
    }
    else
    {
        # Disabled PowerShell v2 for Server/Multi-Session SKU
        Remove-WindowsFeature -Name PowerShell-V2 -ErrorAction Stop | Out-Null
        Write-Host "Powershell v2.0 feature has been disabled."
    }
```

**Comment by tmmuessig** [comment]
@brmcmill - After Robert and I discussed this we feel that this should not be implemented by VDOT as we start touching on "Security Related" settings.  Since this is more of a security related item and does not add to the performance of AVD, we have decided not to implement this.

We do appreciate the input and we may look at this again down the road.

**Comment by brmcmill** [comment]
All good thanks @tmmuessig and @robsmi-msfte for the consideration.  I totally understand.  Keep rockin'!
