### ISSUE TITLE
VDOT breaks start menu icons windows apps

### ISSUE THREAD

**Issue by Fruitbiscuit1** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#200]
Hi,

Is it possible that VDOT breaks the start menu icons when searching?
Did some troubleshooting and only seems to happen when i use VDOT.
Ran ".\Windows_VDOT.ps1 -Optimizations All -AdvancedOptimizations All -AcceptEULA -Verbose" With just an edited appxpackages.json.

Windows 10, 22h2 (tested both with and without fslogix)

https://www.reddit.com/r/AZURE/comments/1are38g/azure_virtual_desktop_icons_missing_searching/
This guy seems to have the same issue.

Cheers,

UPDATE; I ran this and it keeps working now:

.\Windows_VDOT.ps1 -Optimizations AppxPackages, scheduledtasks -AcceptEula -Verbose

UPDATE 2: I ran this and it still works:

.\Windows_VDOT.ps1 -Optimizations autologgers, networkoptimizations, services, windowsmediaplayer, AppxPackages, scheduledtasks -AcceptEULA -Verbose

UPDATE 3: DefaultUserSettings breaks it. I tested all parameters.

**Comment by Fruitbiscuit1** [comment]
UPDATE; I ran this and it keeps working now:

.\Windows_VDOT.ps1 -Optimizations AppxPackages, scheduledtasks -AcceptEula -Verbose

**Comment by tmmuessig** [comment]
Let me take a look at this. @sandude-ms have you run across this in your testing?

**Comment by robsmi-msfte** [comment]
Hello @Fruitbiscuit1,

We start with Windows 10 22H2, Multi-Session.  I created a host pool just now, using the Windows 10 AVD SKU that comes with the Office 365 apps.  I then ran VDOT that I just downloaded from the 'main' branch.  I ran only the 'DefaultUserSettings'.  I have no problem with any icons on the Start Menu.

From the screen-shot from Reddit, it looks like they have a different version of Teams on there (Work and School).  The Azure SKU installs a different version of Teams.  So, I uninstalled Office, and uninstalled that version of Teams.

I found "Teams (work or school)" and installed that.  I didn't notice anything at first.  Then instead of looking at icons on the Start Menu, I searched Teams, and found this, which matched the Reddit post:

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/4c1cd9a3-4534-4bab-a646-ce474919e410)

I then start with a clean install, no VDOT no nothing, of Windows 10 Enterprise Multi-Session, 22H2, installed Teams Work of School, repeat the above procedure, and get this:

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/001b5d09-586f-425c-a894-1ef03f0c0711)

So, I started again, but this time I removed from the 'DefaultUserSetting.json', all the Explorer optimizations.  I ran that and no immediate effect.  But...knowing what we do there, I was able to reproduce the issue without VDOT, and it's all in on the visual settings.

Open System Properties, then click Advanced tab, then click the "Settings" button in the 'Performance' section.  The setting that is causing this is this one:

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/a5bfc82d-5d87-472e-9441-5c099838188e)

The specific setting is this one:

    {
        "HivePath": "HKLM:\\VDOT_TEMP\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced",
        "KeyName": "IconsOnly",
        "PropertyType": "DWORD",
        "PropertyValue": 1,
        "SetProperty": "True"
    },

If you edit this file before running VDOT, and change 'SetProperty' to 'false', or just delete that block, you should not see that again with VDOT.  For existing users, you can use this code to change it back:

```reg add HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v IconsOnly /t REG_DWORD /d 0```

Thanks,

Robert M. Smith
