### ISSUE TITLE
HKCU settings stored in mixed locations

### ISSUE THREAD

**Issue by brentil** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#202]
I was working on setting up a new VDI and noticed a behavior that I think is a bug.

DefaultUserSettings.json updates the temp loaded VDOT_TEMP copy of the default user hive so its HKCU settings are stored for new user profiles.

PolicyRegSettings.json updates the active running users HKCU registry so only the current loaded user profile gets those settings configured.  I did not see the default user hive that's loaded at VDOT_TEMP also get these settings so new user profiles will be missing the configuration.

Maybe both should be updated in both places, that way the existing user has them all applied and all future profiles do as well?

**Comment by robsmi-msfte** [comment]
Hello @brentil,

Good find.  What I did migrate the setting for HKCU over to 'DefaultUserSettings.json'.  At the same time, I left those settings in the 'PolicyRegSettings.json'.

I also listed you as a contributor in the Readme, since that was a fairly significant find and took a bit of work to resolve.  I currently have that checked into a branch, as I have been doing some testing on Windows 11 23H2.  You can review that current branch as "rs/June_VDOT_changes".

I will close this issue now, because I believe we have addressed your concern.  If that is not the case let us know.

Thank you,

Robert M. Smith
