### ISSUE TITLE
Access Denied when unload HKLM\Default

### ISSUE THREAD

**Issue by shawntmeyer** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#28]
Hello Robert, Tim, and Jason,

I'm seeing on first run through that something seems to be holding open the HKLM\Default registry hive when the Default User Settings tries to unmount this hive. If I run the script a second time, it behaves. I imagine given this that the issue is somewhere in the routine that creates the registry keys when they don't exist.

I think you need to add the following lines of code after the registry functions. Perhaps in a Try{}Catch{} statement to clean up the open handles to the registry.
Try {
     & REG UNLOAD HKLM\Default
}
Catch {
     [GC]::Collect()
     [GC]::WaitForPendingFinalizers()
     Start-Sleep -Seconds 5
     & REG UNLOAD HKLM\Default
}

Thanks,

Shawn Meyer

**Comment by sandude-ms** [comment]
Hello @shawntmeyer,

We have not had any reports of this specific issue.  Do you have any third-party security software running on your reference image?  Do you have any indication of whether the issue is with Reg.exe, or with the folder C:\Users\Default? (as in not being able to flush the file to that folder).

We will look at the code and consider adding it.

Thanks,

Robert M. Smith

**Comment by mherr698** [comment]
Hello Robert,

I have experienced the same issue as a full admin user, Windows 10 build 2009, no third party security software (just Windows Defender).

Regards,
Martin Herr
