### ISSUE TITLE
Windows 10 1909 Visual Optmizations + Script Flags

### ISSUE THREAD

**Issue by maul0r** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#33]
Hi, 
I have noticed that
- When I try to use flags on the script, as in -LGPO:$false the script doesn't execute. Is there something I am doing wrong? 
- The visual styles do not apply properly. After execution of the unmodified script with unmodified settings, I am seeing custom visual effects, but all selected except "save taskbar thumbnail previews" and "show shadows under mouse pointer" 
In order for me to get visual styles to work, I need to set HKLM Options for the styles. 
Am I the only one who has these problems, if so, what am I doing wrong? I tried applying the script to freshly installed W10-1909 as well and no joy. 
Appreciate any advise you could give me?

**Comment by tmmuessig** [comment]
Hi @maul0r 

For the first question, you only need to specify the portions you want to run.  For instance if you wanted everything except LGPO you would run the following:

`Win10_VirtualDesktop_Optimize.ps1 -WindowsMediaPlayer -AppxPackages -ScheduledTasks -DefaultUserSettings -Autologgers -Services -NetworkOptimizations- DiskCleanup`

We can look into possibly supporting the -Option:$False in the future, but right now it is not coded as such.

@sandude-ms  - Do you have any ideas as to the second question?

**Comment by maul0r** [comment]
Is there an update? 

I have one more bit of information not sure how relevant this is to other people: When you disable Passive Polling on the NCSI indicator, I get "not connected to internet". Maybe this is because it is actually not connected. However, If I enable it again, it will contact the cooperate host and will show internet access. I have now set ["Do not show the "local access only" network icon" ](https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.NetworkConnections::NC_DoNotShowLocalOnlyIcon) to mitigate this.

**Comment by joelt-code** [comment]
Network Connectivity Status Indicator (NCSI) is designed to be responsive to network conditions, so it examines the connectivity of a network in a variety of ways. One test failed, NCSI may report an error, even if the networking actually can be accessed fully.

Sometimes, we can access the http://www.msftncsi.com/ncsi.txt file in IE, but the NCSI still fails. It is because the NCSI traffic is not sent via IE but via the WinHTTP component and uses proxy specifically. A proxy server that requires user authentication won't allow it to access the Internet. Basically, NCSI must perform extra steps in an environment that has proxy servers. Web Proxy Automatic Discovery (WPAD) proxy detection is recommended. If WPAD is not used, configure WinHTTP proxy settings to help NCSI:

netsh winhttp set proxy command

For how to disable NCSI, please kindly refer to the workaround in the following article:
https://support.microsoft.com/en-us/help/4494446/an-internet-explorer-or-edge-window-opens-when-your-computer-connects

Meanwhile, I found another article related to Microsoft Connection Test (NCSI) and office 365 for your reference.
https://purepcs.co.uk/kb/microsoft-connection-test-ncsi-and-office-365/
Please Note: Since the websites are not hosted by Microsoft, the links may change without notice. Microsoft does not guarantee the accuracy of this information.

Hope my answer will help you.

**Comment by maul0r** [comment]
Thank you for your detailed explanation @joelt-code. 
We are actually using it in an offline network - so we have only specified the cooperate DNS node. I guess in order to get this working as expected, we would need to generate the relevant DNS entries to mimic this behavior - I guess we can leave it disabled then as I don't have the power to do this in DNS. 

@sandude-ms  Any idea about the visual stuff? 

@anyone
I have also witnessed, that when using these optimization settings with Horizon View, it seems to take longer or fail sometimes even to connect to a virtual desktop. Anyone seen anything like that? It might be just a conflict in our environment.

**Comment by sandude-ms** [comment]
Hello @maul0r,

The visual settings are applied per-user.  A regular user can't check them without elevating.  You may want to determine if those settings are those of the actual user, or of a user that already had a profile created.  This is because the visual effects settings only apply to users created after the settings in this tool are applied.  They won't change the visual settings if the profile has already been created.

If you want to apply those settings to user profiles that have been created you can, but it would take a little work ahead of time.  You could create a script that the user's could run, or you could use group policy to set these settings as a preference.

And back to the user versus machine settings...the method we use to edit the default user profile file (NTUser.dat) is to load it during running the tool, making the settings to that file, then unloading it.  When you load a registry file using Reg.exe or Regedit.exe, you load that as a subkey of HKLM.  That's what you see if you view the default settings text file.

But if you create a new user on an optimized machine, then log on, then check the visual setting, you should see that only 3 settings are checked in visual settings:

- Show shadows under mouse pointer
- Show shadows under windows
- Smooth edges of screen fonts

Thanks,

Robert M. Smith

**Comment by maul0r** [comment]
So I have just installed a W10 1909 Enterprise in VMware Workstation, patched it and applied the optimizations w/o any changes. I then logged in as testuser (so new profile) and I get this:

![vfx](https://user-images.githubusercontent.com/30387863/106326264-7d255f00-627c-11eb-89f6-754f51bfbeb2.PNG)

**Comment by sandude-ms** [comment]
Hello @maul0r,

We are about to merge a branch into "main" that has logging enabled.  This logging may be useful here.  Try downloading the VDOT tool from this branch:

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/tree/tmm-PolicyJSON

Then run just the default user settings.

.\Win10_VirtualDesktop_Optimize.ps1 -DefaultUserSettings -Verbose

Let's check the screen and the log to see what's happening.

Thanks,

Robert Smith

**Comment by sandude-ms** [comment]
@maul0r, I was mistaken, we have had logging in "main" for several months now.  Just download a new copy from the "main" branch, run it as I indicated above, and after running, refer to the .CSV log file in the VDOT folder.  Look for any [ERROR] entries.
