### ISSUE TITLE
Question: Rationale behind disabling Photos and Snip&Sketch apps

### ISSUE THREAD

**Issue by MrR0bert** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#43]
Could someone please explain why the following apps are uninstalled as part of the optimization, I could not find this in the documentation / readme:

1. Microsoft.ScreenSketch
2. Microsoft.Windows.Photos

During our PoC phase we found that for example opening images (just ordinary .png or .jpg files) after the optimization has run, results in a prompt for the user saying: "you'll need a new app to open this ms-paint link". This is caused by the Photos app being disabled.

Also, the Snip & Sketch app will replace the snipping tool (as per the notification in the 'old' snipping tool):
![image](https://user-images.githubusercontent.com/20636874/106164339-22133f80-618a-11eb-84eb-10e1afd41393.png)

So we're also curious to know why this app was removed as part of the optimization.

**Comment by sandude-ms** [comment]
Hello @MrR0bert,

The apps that are in the list in the tool, are all the apps that CAN be removed in a supported manner.  We did that in case someone wants to remove those apps...not because there is any rational reason to do so.  We urge consumers of this tool to evaluate every setting available, for applicability to their specific environment, and to customize accordingly.

Thanks,

Robert M. Smith
