### ISSUE TITLE
Access denied error of REG UNLOAD HKLM\VDOT_TEMP

### ISSUE THREAD

**Issue by bmbadr** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#70]
I got an access denied error when running the script because of the command "& REG UNLOAD HKLM\VDOT_TEMP | Out-Null"
I've solved it by replacing it with:
Start-Process reg-ArgumentList "LOAD HKLM\VDOT_TEMP C:\Users\Default\NTUSER.DAT" -PassThru -Wait 
#& REG LOAD HKLM\VDOT_TEMP C:\Users\Default\NTUSER.DAT | Out-Null  

[GC]::Collect() 
Start-Process reg-ArgumentList "UNLOAD HKLM\VDOT_TEMP" -PassThru -Wait 
#& REG UNLOAD HKLM\VDOT_TEMP | Out-Null

**Comment by msft-jasonparker** [comment]
@bmbadr Thanks for the feedback, we would be happy to accept a PR from you if you'd like to submit this change in a new branch.

**Comment by sandude-ms** [comment]
We will look at updating the PowerShell code to include this suggestion.  We thank you for using the VDOT tool and contributing to this project.

**Comment by ii-batman** [comment]
> > I got an access denied error when running the script because of the command "& REG UNLOAD HKLM\VDOT_TEMP | Out-Null"
> I've solved it by replacing it with:
> Start-Process reg-ArgumentList "LOAD HKLM\VDOT_TEMP C:\Users\Default\NTUSER.DAT" -PassThru -Wait
> #& REG LOAD HKLM\VDOT_TEMP C:\Users\Default\NTUSER.DAT | Out-Null
> 
> Start-Process reg-ArgumentList "UNLOAD HKLM\VDOT_TEMP" -PassThru -Wait
> #& REG UNLOAD HKLM\VDOT_TEMP | Out-Null

Hi 
I get the same access denied error, tried your fix and still errors.
Would you be able to share your full script please?

> [dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\DiagLog\
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: At C:\buildartifacts\working\W10_Optim\Virtual-Desktop-Optimization-Tool-main\Win10_VirtualDesktop_Optimize.ps1:284
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReadyBoot\
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WDIContextLog\
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WiFiDriverIHVSession\
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WiFiSession\
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WinPhoneCritical\
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: [VDI Optimize] Disable Services
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: char:1
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: + Start-Process reg-ArgumentList "LOAD HKLM\VDOT_TEMP C:\Users\Default\ ...
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Processing Services Configuration File
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Stop Service autotimesvc - Cellular Time service: this service sets time based on NITZ messages
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: At C:\buildartifacts\working\W10_Optim\Virtual-Desktop-Optimization-Tool-main\Win10_VirtualDesktop_Optimize.ps1:287
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: from a Mobile Network
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: char:1
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Disable Server autotimesvc - Cellular Time service: this service sets time based on NITZ
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: + Start-Process reg-ArgumentList "UNLOAD HKLM\VDOT_TEMP" -PassThru -Wai ...
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: messages from a Mobile Network
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Stop Service BcastDVRUserService - This user service is used for Game Recordings and Live
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: Broadcasts
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Disable Server BcastDVRUserService - This user service is used for Game Recordings and Live
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: Broadcasts
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Stop Service defragsvc - Optimize drives
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Disable Server defragsvc - Optimize drives
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: New-Item : The parameter is incorrect.
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Stop Service DiagSvc - Diagnostic Execution Service
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: At C:\buildartifacts\working\W10_Optim\Virtual-Desktop-Optimization-Tool-main\Win10_VirtualDesktop_Optimize.ps1:321
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Disable Server DiagSvc - Diagnostic Execution Service
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: char:35
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Stop Service DiagTrack - Connected User Experiences and Telemetry service, manages the event
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: driven collection and transmission of diagnostic and usage information (used to improve the experience and quality of
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: the Windows Platform) when the diagnostics and usage privacy option settings are enabled under Feedback and
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: Diagnostics.
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: + ...             $newKey = New-Item -Path ("{0}" -f $Item.HivePath) -Force
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: +                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT     azure-arm: VERBOSE: Attempting to Disable Server DiagTrack - Connected User Experiences and Telemetry service, manages the event
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:     + CategoryInfo          : OpenError: (HKEY_LOCAL_MACH...plorer\Advanced:String) [New-Item], IOException
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:     + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.NewItemCommand
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm:
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: Test-Path : Cannot bind argument to parameter 'Path' because it is null.
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: At C:\buildartifacts\working\W10_Optim\Virtual-Desktop-Optimization-Tool-main\Win10_VirtualDesktop_Optimize.ps1:322
[dbcf8f1d-4e2a-436c-93cf-4d6a3012cd68] PACKER OUT ==> azure-arm: char:45

**Comment by bmbadr** [comment]
[Win10_VirtualDesktop_Optimize.txt](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/files/6689949/Win10_VirtualDesktop_Optimize.txt)

Here the full script. I just changed what I mentioned earlier and ran it using this:
Set-Location -path $Temp\Optimization-Tool\Virtual-Desktop-Optimization-Tool-main
.\Win10_VirtualDesktop_Optimize.ps1 -Optimizations 'All'

**Comment by ii-batman** [comment]
@bmbadr 
Brill! 
Resolved my issue first time.
Thanks so much.
