### ISSUE TITLE
Error when running the Win10_VirtualDesktop_Optimize.ps1 script

### ISSUE THREAD

**Issue by ii-batman** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#84]
Error when running the Win10_VirtualDesktop_Optimize.ps1 script as admin:

```
[VDI Optimize] Set Default User Settings
reg.exe : ERROR: Access is denied.
At C:\optimize\Virtual-Desktop-Optimization-Tool-main\Win10_VirtualDesktop_Optimize.ps1:329 char:17
+                 & REG UNLOAD HKLM\VDOT_TEMP | Out-Null
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Access is denied.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[VDI Optimize] Disable Autologgers
```

**Comment by tmmuessig** [comment]
Hi @ii-batman 

Not knowing when you downloaded the script/repo, can you tell me if you have a log file in the script directory with a .csv extension?  If you don't have that can you look in the event logs under "Applications and Services Logs > Virtual Desktop Optimization" and see if there is anything else logged from the source "DefaultUserSettings".

**Comment by ii-batman** [comment]
@tmmuessig 
Thanks for your quick reply.
I just downloaded the files today.
I came to your repo via Jason's repo: https://github.com/danielsollondon/azvmimagebuilder/blob/master/solutions/14_Building_Images_WVD/1_Optimize_OS_for_WVD.ps1
Which by the way is referencing a not existing folder on your Git, did you guys tidy up recently?
Anyway I reran the script and it's fine now, not reg related errors.
Will you guys be creating a folder for 21H1?
Great stuff you have here, learning lots!
Cheers

**Comment by tmmuessig** [comment]
Glad everything is working now :)

We have done some cleanup recently, so that would explain the missing folder issue as well.

We will not be creating anything new for 21H1 as the setting are the same for 20H2 (2009) so I would recommend using that. We will be releasing updated configuration items for 21H2 though.

Closing this as your issue appears to be resolved, but if you have any more issues, feel free to open this back up or start a new issue, happy to help.
